// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package collatzpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CollatzServiceClient is the client API for CollatzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollatzServiceClient interface {
	Seed(ctx context.Context, in *SeedRequest, opts ...grpc.CallOption) (*SeedResponse, error)
}

type collatzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollatzServiceClient(cc grpc.ClientConnInterface) CollatzServiceClient {
	return &collatzServiceClient{cc}
}

func (c *collatzServiceClient) Seed(ctx context.Context, in *SeedRequest, opts ...grpc.CallOption) (*SeedResponse, error) {
	out := new(SeedResponse)
	err := c.cc.Invoke(ctx, "/collatz.CollatzService/Seed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollatzServiceServer is the server API for CollatzService service.
// All implementations must embed UnimplementedCollatzServiceServer
// for forward compatibility
type CollatzServiceServer interface {
	Seed(context.Context, *SeedRequest) (*SeedResponse, error)
	mustEmbedUnimplementedCollatzServiceServer()
}

// UnimplementedCollatzServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCollatzServiceServer struct {
}

func (UnimplementedCollatzServiceServer) Seed(context.Context, *SeedRequest) (*SeedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Seed not implemented")
}
func (UnimplementedCollatzServiceServer) mustEmbedUnimplementedCollatzServiceServer() {}

// UnsafeCollatzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollatzServiceServer will
// result in compilation errors.
type UnsafeCollatzServiceServer interface {
	mustEmbedUnimplementedCollatzServiceServer()
}

func RegisterCollatzServiceServer(s grpc.ServiceRegistrar, srv CollatzServiceServer) {
	s.RegisterService(&CollatzService_ServiceDesc, srv)
}

func _CollatzService_Seed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollatzServiceServer).Seed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/collatz.CollatzService/Seed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollatzServiceServer).Seed(ctx, req.(*SeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollatzService_ServiceDesc is the grpc.ServiceDesc for CollatzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollatzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collatz.CollatzService",
	HandlerType: (*CollatzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Seed",
			Handler:    _CollatzService_Seed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "collatz.proto",
}
